---
- hosts: docker_hosts
  become: yes
  tasks:
    - name: install docker
      apt:
        name: docker.io
        state: latest
    
    - name: enable and start docker
      service:
        name: docker
        enabled: yes
        state: started